import {N,PAD,CELL,px,same,inside,reflect,opposite,axisEnd,extendAxis,prepare,fold,rotate,timeline,vertexName,guideSequence,pageTurn,initialDirection,orientPath,joinBoundary} from './geometry.js';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
function el(tag,attrs={},parent){const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);parent?.append(n);return n}
function label(p,value,attrs,parent){const n=el('text',{x:p.x,y:p.y,...attrs},parent);n.textContent=value;return n}
const initial=()=>({points:[],axis:[{x:10,y:0},{x:10,y:20}],center:{x:10,y:10},complete:false,direction:null});
const activities={step:{line:initial(),point:initial()},live:{line:initial(),point:initial()}};let activity='step',models=activities.step;let mode='line',tool='draw',pending=null,hover=null,cursor={x:5,y:7},busy=false,animation=null,errorTimer,selected=null,drag=null,lastTap=null,deleteHit=null;
const histories={step:{line:[],point:[]},live:{line:[],point:[]}},history=()=>histories[activity][mode],snapshot=()=>structuredClone(model());
function remember(state=snapshot()){history().push(state);if(history().length>100)history().shift()}
function updateDirection(){const m=model();if(!m.direction)m.direction=initialDirection(m.points,mode,m.axis,m.center)}
const model=()=>models[mode],target=p=>mode==='line'?reflect(p,model().axis):opposite(p,model().center),plan=()=>{const m=model(),p=prepare(m.points,mode,m.axis,m.center);p.path=orientPath(p.path,m.points,mode,m.axis,m.center,m.direction);if(!p.error)Object.assign(p,joinBoundary(p.path,mode,m.axis,m.center));return p};
function dismissError(){clearTimeout(errorTimer);$('error-toast').hidden=true}
function error(message){clearTimeout(errorTimer);$('error-toast').textContent=message;$('error-toast').hidden=false;errorTimer=setTimeout(dismissError,4200)}
function announce(text){$('live-status').textContent=text}
function buildGrid(){const g=$('grid-layer');el('rect',{x:PAD,y:PAD,width:600,height:600,fill:'#fff'},g);for(let i=0;i<=N;i++){const v=PAD+i*CELL,cls=i%5===0?'grid-major':'grid-line';el('line',{x1:v,y1:PAD,x2:v,y2:636,class:cls},g);el('line',{x1:PAD,y1:v,x2:636,y2:v,class:cls},g);if(i%5===0){label({x:v,y:23},i,{class:'grid-number'},g);label({x:19,y:v+4},i,{class:'grid-number'},g)}}for(let y=0;y<=N;y++)for(let x=0;x<=N;x++)el('circle',{cx:PAD+x*CELL,cy:PAD+y*CELL,r:1.4,class:'grid-dot'},g)}
function pointsAttr(ps){return ps.map(p=>{const q=px(p);return `${q.x},${q.y}`}).join(' ')}
function chain(ps,parent,color='#1b674f'){if(ps.length<2)return;return el('polyline',{points:pointsAttr(ps),class:'shape',stroke:color},parent)}
function vertices(ps,parent,color,prime=false,skip=[],source=ps){const named=plan().path;ps.forEach((p,i)=>{if(skip.some(q=>same(p,q)))return;const q=px(p),index=named.findIndex(point=>same(point,source[i]));el('circle',{cx:q.x,cy:q.y,r:4.3,fill:'#fff',stroke:color,'stroke-width':2},parent);label({x:q.x+(prime?9:-9),y:q.y-10},vertexName(index)+(prime?'′':''),{class:'vertex-label',fill:color,'text-anchor':prime?'start':'end'},parent)})}
function renderReference(){const g=$('reference-layer');g.replaceChildren();if(mode==='line'){const ends=extendAxis(model().axis).map(px);if(ends.length===2){el('line',{x1:ends[0].x,y1:ends[0].y,x2:ends[1].x,y2:ends[1].y,class:'axis-line'},g);const top=ends.reduce((a,b)=>a.y<b.y?a:b);label({x:Math.min(590,Math.max(70,top.x+32)),y:Math.max(54,top.y+18)},'대칭축',{class:'axis-label','text-anchor':'middle'},g)}if(tool==='axis'&&!busy)model().axis.forEach((p,i)=>{const q=px(p);el('circle',{cx:q.x,cy:q.y,r:7,fill:'#fff4e5',stroke:'#bb742d','stroke-width':2,'data-axis-handle':i},g)})}else{const c=px(model().center);el('circle',{cx:c.x,cy:c.y,r:9,fill:'#fff4e5',stroke:'#dc9354','stroke-width':1.5},g);el('circle',{cx:c.x,cy:c.y,r:3.5,fill:'#bf742e'},g);label({x:Math.max(85,Math.min(c.x,587)),y:c.y>600?c.y-20:c.y+25},'대칭의 중심',{class:'axis-label','text-anchor':'middle'},g)}if(pending){const p=px(pending);el('circle',{cx:p.x,cy:p.y,r:6,fill:'#e4a425'},g)}}
function render(){const m=model(),p=plan();for(const id of ['fill-layer','shape-layer','point-layer'])$(id).replaceChildren();if((m.complete||activity==='live')&&!p.error){el('polygon',{points:pointsAttr(p.outline),fill:'#e6f0de','data-complete-boundary':'true'},$('fill-layer'));}if((m.complete&&!p.error)||activity==='live'){const mirror=p.path.map(target);chain(mirror,$('shape-layer'),'#3e70d4');vertices(mirror,$('point-layer'),'#3e70d4',true,p.path,p.path)}chain(p.path,$('shape-layer'));vertices(p.path,$('point-layer'),'#1b674f');renderReference();$('point-count').textContent=`찍은 점 ${m.points.length}개`;$('make').disabled=busy||m.points.length<3||tool!=='draw';$('make').querySelector('span').textContent=busy?'대칭 만드는 중':m.complete?'대칭 다시 보기':'대칭 만들기';$('undo').disabled=busy||!history().length;$('clear').disabled=busy||!m.points.length;for(const id of ['line-mode','point-mode','axis-tool','center-tool','draw-tool','example'])$(id).disabled=busy;renderCursor()}
function ui(){$('make').hidden=activity==='live';$('activity-badge').textContent=activity==='live'?'실시간 대칭 그리기':'대칭 완성하기';$('drawing-title').textContent=activity==='live'?'함께 그리기':'반쪽 그리기';$('line-mode').setAttribute('aria-pressed',mode==='line');$('point-mode').setAttribute('aria-pressed',mode==='point');$('mode-badge').textContent=mode==='line'?'선대칭도형':'점대칭도형';for(const t of ['axis','center','draw'])$(t+'-tool').setAttribute('aria-pressed',tool===t);render()}
function clearTransient(){closePointMenu();lastTap=null;selected=null;drag=null;for(const id of ['guide-layer','motion-layer','cursor-layer'])$(id).replaceChildren();$('guide-layer').setAttribute('opacity','1');$('angle-pill').hidden=true;dismissError()}
function chooseMode(next){if(busy)return;mode=next;tool='draw';pending=null;clearTransient();ui()}
function chooseTool(t){if(busy)return;if(t==='axis')mode='line';if(t==='center')mode='point';tool=t;pending=null;clearTransient();ui()}
function select(p){if(busy)return;const m=model();dismissError();if(tool==='axis'){if(selected?.axis){moveSelected(p);return}const hit=!pending?hitAxis(p):null;if(hit){selected=hit;renderCursor();return}if(!pending){pending=p;ui();return}const q=axisEnd(pending,p);if(!q){error('서로 다른 두 점을 선택해 주세요.');return}remember();m.axis=[pending,q];m.complete=false;pending=null;tool='draw';ui();return}if(tool==='center'){remember();m.center=p;m.complete=false;tool='draw';ui();return}if(selected){moveSelected(p);return}const hit=hitVertex(p);if(hit){selected=hit;renderCursor();return}if(m.points.length>=26){error('최대 26개의 점을 찍을 수 있어요.');return}if(mode==='point'&&same(p,m.center)){error('대칭의 중심에는 꼭짓점을 찍을 수 없어요.');return}const candidate=[...m.points,p];if(mode==='line'&&activity!=='live'){const [a,b]=m.axis,sign=q=>(b.x-a.x)*(q.y-a.y)-(b.y-a.y)*(q.x-a.x);if(candidate.some(q=>sign(q)>1e-7)&&candidate.some(q=>sign(q)< -1e-7)){error('대칭축 한쪽에 점을 찍어 주세요.');return}}if(!inside(target(p))){error('이 점의 대응점이 모눈 밖으로 나가요.');return}remember();m.points.push(p);updateDirection();m.complete=false;clearTransient();render()}
function hitAxis(p){const index=model().axis.findIndex(q=>same(p,q));return index<0?null:{index,axis:true}}
function selectedPoint(hit){return hit.axis?model().axis[hit.index]:model().points[hit.index]}
function hitVertex(p){const m=model();let index=m.points.findIndex(q=>same(p,q));if(index>=0)return {index,mirror:false};if(m.complete||activity==='live'){index=m.points.map((q,i)=>({i,d:Math.hypot(p.x-target(q).x,p.y-target(q).y)})).filter(q=>q.d<=.72).sort((a,b)=>a.d-b.d)[0]?.i??-1;if(index>=0)return {index,mirror:true}}return null}
function moveError(p,index){const m=model();if(!p||!inside(p))return '모눈 안으로 옮겨 주세요.';if(m.points.some((q,i)=>i!==index&&same(p,q)))return '다른 점과 겹치지 않는 곳으로 옮겨 주세요.';if(mode==='point'&&same(p,m.center))return '대칭의 중심에는 꼭짓점을 놓을 수 없어요.';if(!inside(target(p)))return '이 점의 대응점이 모눈 밖으로 나가요.';if(mode==='line'&&activity!=='live'){const [a,b]=m.axis,sign=q=>(b.x-a.x)*(q.y-a.y)-(b.y-a.y)*(q.x-a.x),ps=m.points.map((q,i)=>i===index?p:q);if(ps.some(q=>sign(q)>1e-7)&&ps.some(q=>sign(q)<-1e-7))return '대칭축 한쪽에 점을 놓아 주세요.'}return null}
function moveSelected(destination,preview=false){if(!selected||busy)return false;if(selected.axis){const m=model(),p=destination;if(!p||!inside(p)||same(p,m.axis[1-selected.index])){if(!preview)error('모눈 안의 서로 다른 두 점을 선택해 주세요.');return false}if(!preview&&!same(p,drag?drag.original:m.axis[selected.index]))remember(drag?drag.before:snapshot());m.axis[selected.index]={...p};m.complete=(drag?drag.complete:m.complete)&&!plan().error;if(!preview){selected=null;announce('대칭축을 옮겼습니다.')}render();return true}const p=destination&&(selected.mirror?{x:Math.round(target(destination).x),y:Math.round(target(destination).y)}:destination),message=moveError(p,selected.index);if(message){if(!preview)error(message);return false}const m=model(),keepComplete=drag?drag.complete:m.complete;if(!preview&&!same(p,drag?drag.original:m.points[selected.index]))remember(drag?drag.before:snapshot());m.points[selected.index]={...p};m.complete=keepComplete&&!plan().error;dismissError();if(!preview){selected=null;announce('선택한 점을 옮겼습니다.')}render();return true}
function closePointMenu(){deleteHit=null;$('point-menu').hidden=true}
function openPointMenu(hit,p){if(!hit||busy)return;deleteHit=hit;selected=hit;const q=px(p);$('point-menu').style.left=Math.max(9,Math.min(84,q.x/672*100))+'%';$('point-menu').style.top=Math.max(2,Math.min(88,q.y/672*100))+'%';$('point-menu').hidden=false;renderCursor()}
$('delete-point').onclick=()=>{if(!deleteHit||busy)return;remember();const m=model(),keep=m.complete;m.points.splice(deleteHit.index,1);m.complete=keep&&!plan().error;clearTransient();render();announce('점을 삭제했습니다.');$('board').focus({preventScroll:true})};
function renderCursor(){const g=$('cursor-layer');g.replaceChildren();$('board').dataset.moving=String(!!drag);$('board').dataset.vertexHover=String(!!(hover&&(tool==='draw'?hitVertex(hover):tool==='axis'&&hitAxis(hover))));if(busy)return;if(selected){const p=selectedPoint(selected);if(p){const q=px(selected.mirror?target(p):p);el('circle',{cx:q.x,cy:q.y,r:10,fill:'#e4a42522',stroke:'#d69a21','stroke-width':2.5,'data-selected-vertex':'true'},g)}}if(!hover)return;let p=hover;if(tool==='axis'&&pending){const q=axisEnd(pending,p);if(q){const a=px(pending),b=px(q);el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'axis-line'},g);p=q}}const q=px(p);el('circle',{cx:q.x,cy:q.y,r:7,fill:'none',stroke:'#76954f','stroke-width':1.5},g)}
function eventPoint(e){const matrix=$('board').getScreenCTM();if(!matrix)return null;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());const x=Math.round((p.x-PAD)/CELL),y=Math.round((p.y-PAD)/CELL);return x<0||x>20||y<0||y>20?null:{x,y}}
function cancelDrag(){if(drag){if(drag.axis)model().axis[drag.index]=drag.original;else model().points[drag.index]=drag.original;model().complete=drag.complete;const id=drag.id;drag=null;if($('board').hasPointerCapture(id))$('board').releasePointerCapture(id)}selected=null;render()}
$('board').addEventListener('pointermove',e=>{hover=eventPoint(e);if(drag&&e.pointerId===drag.id){if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)drag.moved=true;if(drag.moved)moveSelected(hover,true)}renderCursor()});
$('board').addEventListener('pointerleave',()=>{hover=null;renderCursor()});
$('board').addEventListener('pointerdown',e=>{if(e.button!==0||busy||drag)return;const p=eventPoint(e);if(!p)return;closePointMenu();e.preventDefault();$('board').focus({preventScroll:true});cursor=p;hover=p;const hit=tool==='draw'?hitVertex(p):tool==='axis'&&!pending?hitAxis(p):null;if(selected&&(!hit||hit.index!==selected.index||hit.mirror!==selected.mirror)){moveSelected(p);return}if(hit){selected=hit;drag={id:e.pointerId,index:hit.index,axis:!!hit.axis,original:{...selectedPoint(hit)},complete:model().complete,before:snapshot(),x:e.clientX,y:e.clientY,moved:false};$('board').setPointerCapture(e.pointerId);renderCursor()}else select(p)});
$('board').addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.id)return;const d=drag,p=eventPoint(e);if(d.moved){if(!moveSelected(p)){if(d.axis)model().axis[d.index]=d.original;else model().points[d.index]=d.original;model().complete=d.complete}lastTap=null}else if(!d.axis){const now=performance.now();if(lastTap&&lastTap.index===d.index&&lastTap.mirror===selected?.mirror&&now-lastTap.time<450){openPointMenu(selected,p);lastTap=null}else lastTap={index:d.index,mirror:selected?.mirror,time:now}}drag=null;if($('board').hasPointerCapture(e.pointerId))$('board').releasePointerCapture(e.pointerId);render()});
$('board').addEventListener('dblclick',e=>{if(tool!=='draw'||busy)return;const p=eventPoint(e);if(p){e.preventDefault();openPointMenu(hitVertex(p),p)}});
$('board').addEventListener('pointercancel',()=>cancelDrag());
$('board').addEventListener('lostpointercapture',()=>{if(drag)cancelDrag()});
$('board').addEventListener('keydown',e=>{const ds={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(busy)return;if(ds[e.key]){e.preventDefault();const [x,y]=ds[e.key];cursor={x:Math.max(0,Math.min(20,cursor.x+x)),y:Math.max(0,Math.min(20,cursor.y+y))};hover=cursor;renderCursor()}else if(e.key==='Enter'||e.key===' '){e.preventDefault();select(cursor)}else if(e.key==='Backspace'){e.preventDefault();$('undo').click()}else if(e.key==='Escape'){cancelDrag();chooseTool('draw')}});
$('line-mode').onclick=()=>chooseMode('line');$('point-mode').onclick=()=>chooseMode('point');for(const t of ['axis','center','draw'])$(t+'-tool').onclick=()=>chooseTool(t);
$('undo').onclick=()=>{if(busy||!history().length)return;cancelDrag();models[mode]=history().pop();clearTransient();render();announce('이전 상태로 되돌렸습니다.')};$('clear').onclick=()=>{if(busy)return;remember();model().direction=null;model().points=[];model().complete=false;clearTransient();render()};
$('example').onclick=()=>{if(busy)return;remember();models[mode]=initial();model().points=mode==='line'?[{x:10,y:8},{x:3,y:4},{x:5,y:16},{x:10,y:14}]:[{x:3,y:5},{x:13,y:5},{x:13,y:10},{x:17,y:15}];updateDirection();tool='draw';pending=null;clearTransient();ui()};
function drawGuides(progress=1){const g=$('guide-layer');g.replaceChildren();const list=animation.guides;list.forEach((p,i)=>{const u=mode==='point'?Math.max(0,Math.min(1,progress*list.length-i)):progress;if(u<=0)return;const r=target(p),a=px(p),end={x:p.x+(r.x-p.x)*u,y:p.y+(r.y-p.y)*u},b=px(end);el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'guide','data-guide-order':i,'data-progress':u},g);if(u<1){el('circle',{cx:b.x,cy:b.y,r:4,fill:'#bd8639'},g)}else if(mode==='point')vertices([r],g,'#3e70d4',true,animation.plan.path,[p])})}
function drawPage(progress,g){const path=animation.plan.path,axis=model().axis,t=progress*progress*(3-2*progress);const samples=[];path.forEach((p,i)=>{const q=path[(i+1)%path.length];for(let j=0;j<16;j++)samples.push({x:p.x+(q.x-p.x)*j/16,y:p.y+(q.y-p.y)*j/16})});const ps=samples.map(p=>pageTurn(p,axis,t));el('polygon',{points:pointsAttr(path),fill:'#eaf2db',opacity:.75},g);el('polygon',{points:pointsAttr(ps.map(p=>({x:p.x+.25*Math.sin(Math.PI*t),y:p.y+.35*Math.sin(Math.PI*t)}))),class:'paper-shadow',opacity:.25*Math.sin(Math.PI*t)},g);el('polygon',{points:pointsAttr(ps),fill:t<.5?'url(#paper-front)':'url(#paper-back)',class:'paper-sheet','data-page-turn':t},g);const moving=path.map(p=>pageTurn(p,axis,t));chain(moving,g,'#3e70d4');vertices(moving,g,'#3e70d4',true,[],path)}
function frame(ms){const m=model(),s=timeline(ms,mode,animation.reduced,animation.guides.length),g=$('motion-layer');$('board').dataset.phase=s.phase;g.replaceChildren();$('guide-layer').setAttribute('opacity',s.guides?'1':'0');if(s.guides)drawGuides(s.phase==='guides'?s.progress:1);if(s.phase!==animation.phase){animation.phase=s.phase;if(s.phase==='blink'){m.complete=true;render();announce('하나의 대칭도형이 완성되었습니다.')}}
 if(s.phase==='move'){const t=s.progress*s.progress*(3-2*s.progress);if(mode==='line')drawPage(s.progress,g);else{const ps=animation.plan.path.map(p=>rotate(p,m.center,t));chain(ps,g,'#3e70d4');vertices(ps,g,'#3e70d4',true,[],animation.plan.path)}$('angle-pill').hidden=false;$('angle-pill').textContent=Math.round(t*180)+'°'}else{$('angle-pill').hidden=true}
 if(s.phase==='done'){const resolve=animation.resolve;busy=false;animation=null;clearTransient();m.complete=true;render();resolve(true);return true}return false;
}
function makeSymmetry(){if(activity==='live')return Promise.resolve(false);if(busy)return Promise.reject(Error('Animation is running.'));const p=plan();if(p.error){error(p.error);return Promise.resolve(false)}clearTransient();model().complete=false;busy=true;render();return new Promise(resolve=>{animation={start:performance.now(),pause:null,phase:null,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,resolve,plan:p,guides:guideSequence(p.path,mode,model().axis,model().center),raf:null};function tick(now){if(!animation||animation.pause!==null)return;if(!frame(now-animation.start))animation.raf=requestAnimationFrame(tick)}animation.tick=tick;animation.raf=requestAnimationFrame(tick)})}
$('make').onclick=()=>makeSymmetry().catch(()=>{});
document.addEventListener('visibilitychange',()=>{if(!animation)return;if(document.hidden){animation.pause=performance.now();cancelAnimationFrame(animation.raf)}else if(animation.pause!==null){animation.start+=performance.now()-animation.pause;animation.pause=null;animation.raf=requestAnimationFrame(animation.tick)}});
function stopAnimation(){if(!animation)return;cancelAnimationFrame(animation.raf);const resolve=animation.resolve;animation=null;busy=false;model().complete=false;resolve(false)}
function openActivity(next){stopAnimation();cancelDrag();activity=next;models=activities[next];tool='draw';pending=null;hover=null;clearTransient();$('home').hidden=true;$('workspace').hidden=false;ui();$('draw-tool').focus({preventScroll:true})}
function openHome(){stopAnimation();cancelDrag();pending=null;hover=null;clearTransient();$('workspace').hidden=true;$('home').hidden=false;$('start-'+activity).focus({preventScroll:true})}
$('start-step').onclick=()=>openActivity('step');$('start-live').onclick=()=>openActivity('live');$('home-button').onclick=openHome;
function fullscreenLabel(){const active=!!document.fullscreenElement||document.body.classList.contains('pseudo-fullscreen');$('fullscreen').querySelector('span').textContent=active?'전체화면 해제':'전체화면';$('fullscreen').setAttribute('aria-label',active?'전체화면 해제':'전체화면');$('fullscreen').setAttribute('aria-pressed',String(active))}
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.body.classList.contains('pseudo-fullscreen'))document.body.classList.remove('pseudo-fullscreen');else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else document.body.classList.add('pseudo-fullscreen')}catch{document.body.classList.toggle('pseudo-fullscreen')}fullscreenLabel()};document.addEventListener('fullscreenchange',fullscreenLabel);document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('pseudo-fullscreen');fullscreenLabel()}});
buildGrid();ui();
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController(),readState=()=>{const p=plan();return {activity,screen:$('home').hidden?'workspace':'home',mode,tool,points:model().points,orderedPath:p.path,completedOutline:model().complete?p.outline:[],axis:model().axis,center:model().center,complete:model().complete,busy,validation:p.error}},register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
 register({name:'read_symmetry_drawing',title:'대칭 그리기 상태 읽기',description:'Read the unordered selected vertices, nearest-point boundary chain, reference, and completed single polygon.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:readState});
 register({name:'configure_symmetry_drawing',title:'대칭 도형 설정하기',description:'Set unordered integer grid points forming one half of a single closed symmetric figure. Line symmetry requires exactly two points on the axis. Point symmetry requires an antipodal endpoint pair. Does not complete the figure.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['line','point']},points:{type:'array',minItems:3,maxItems:26,items:{type:'array',minItems:2,maxItems:2,items:{type:'integer',minimum:0,maximum:20}}},reference:{type:'array',minItems:1,maxItems:2,items:{type:'array',minItems:2,maxItems:2,items:{type:'integer',minimum:0,maximum:20}}}},required:['mode','points','reference'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(busy)throw Error('Animation is running.');const tuple=p=>Array.isArray(p)&&p.length===2&&p.every(v=>Number.isInteger(v)&&v>=0&&v<=20);if(!input||!['line','point'].includes(input.mode)||!Array.isArray(input.points)||input.points.length<3||input.points.length>26||!input.points.every(tuple)||!Array.isArray(input.reference)||!input.reference.every(tuple)||input.reference.length!==(input.mode==='line'?2:1))throw Error('Expected integer grid coordinates from 0 through 20.');const ps=input.points.map(([x,y])=>({x,y})),ref=input.reference.map(([x,y])=>({x,y})),axis=input.mode==='line'?ref:initial().axis,center=input.mode==='point'?ref[0]:initial().center;if(input.mode==='line'){const dx=ref[1].x-ref[0].x,dy=ref[1].y-ref[0].y;if(!dx&&!dy)throw Error('Axis requires two distinct grid points.')}const p=prepare(ps,input.mode,axis,center);if(p.error)throw Error(p.error);openActivity('step');mode=input.mode;remember();models[mode]={points:ps,axis,center,complete:false,direction:initialDirection(ps,mode,axis,center)};tool='draw';pending=null;clearTransient();ui();return readState()}});
 register({name:'complete_symmetry_drawing',title:'대칭 만들기',description:'Animate an open boundary chain by folding or rotating 180 degrees into one closed polygon, then blink correspondence guides every 500 ms for 3000 ms.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},async execute(){if(!await makeSymmetry())throw Error(plan().error);return readState()}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}



